import type { NextPage } from "next";
import Head from "next/head";
import styled from "styled-components";
import { client } from "../libs/client";
import { Blog } from "../types/Blog";
import { ResponseHeader } from "../types/ResponseHeader";
import { BlogCard } from "../components/BlogCard";
import { Pagination } from "../components/Pagination";

type Props = {
  blogs: Blog[];
  totalCount: number;
};

type Res = ResponseHeader & {
  contents: Blog[];
};

const Home: NextPage<Props> = ({ blogs, totalCount }) => {
  return (
    <>
      <Head>
        <title>Blog</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Container>
        <TitleContainer>
          <Headding>ブログのタイトル</Headding>
          <Caption>ブログの説明</Caption>
        </TitleContainer>
        <CardContainer>
          {blogs.map((blog) => (
            <BlogCard key={blog.id} blog={blog} />
          ))}
          <div style={{ width: "300px" }}></div>
          <div style={{ width: "300px" }}></div>
        </CardContainer>
        <Pagination totalCount={totalCount} path="blog" />
      </Container>
    </>
  );
};

export default Home;

export const getStaticProps = async () => {
  const data: Res = await client.get({ endpoint: "blogs?offset=0&limit=5" });

  return {
    props: {
      blogs: data.contents,
      totalCount: data.totalCount,
    },
  };
};

const Container = styled.div`
  width: 80%;
  margin: auto;
  @media (max-width: 600px) {
    width: 95%;
  }
`;

const CardContainer = styled.div`
  width: 100%;
  display: flex;
  gap: 50px;
  justify-content: space-around;
  flex-wrap: wrap;
  padding: 50px 0;
`;
const TitleContainer = styled.div`
  width: 100%;
  text-align: center;
  padding-top: 50px;
`;

const Headding = styled.h1`
  color: #af9d84;
  font-weight: bold;
  font-size: 2rem;
`;

const Caption = styled.p`
  color: #af9d84;
`;
